import type { Metadata } from "next";
import { Space_Grotesk, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { TooltipProvider } from "@/components/ui/tooltip";

const spaceGrotesk = Space_Grotesk({subsets:['latin'],variable:'--font-sans'});

const hindSiliguri = Hind_Siliguri({
  weight: ['400', '600', '700'],
  subsets: ['bengali', 'latin'],
  variable: '--font-hind',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", spaceGrotesk.variable, hindSiliguri.variable)}
    >
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
          <TooltipProvider delayDuration={0}>{children}</TooltipProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}

